# Form implementation generated from reading ui file 'evenodd.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox 


class Ui_evenorodd(object):
    def setupUi(self, evenorodd):
        evenorodd.setObjectName("evenorodd")
        evenorodd.resize(2033, 883)
        self.centralwidget = QtWidgets.QWidget(parent=evenorodd)
        self.centralwidget.setObjectName("centralwidget")
        self.lblNumber = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblNumber.setGeometry(QtCore.QRect(360, 160, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblNumber.setFont(font)
        self.lblNumber.setObjectName("lblNumber")
        self.txtNumber = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtNumber.setGeometry(QtCore.QRect(480, 180, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtNumber.setFont(font)
        self.txtNumber.setObjectName("txtNumber")
        self.btnCheck = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCheck.setGeometry(QtCore.QRect(500, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnCheck.setFont(font)
        self.btnCheck.setObjectName("btnCheck")
        self.lblResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(370, 340, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblResult.setFont(font)
        self.lblResult.setObjectName("lblResult")
        self.txtResult = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtResult.setGeometry(QtCore.QRect(480, 360, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtResult.setFont(font)
        self.txtResult.setObjectName("txtResult")
        evenorodd.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=evenorodd)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2033, 21))
        self.menubar.setObjectName("menubar")
        evenorodd.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=evenorodd)
        self.statusbar.setObjectName("statusbar")
        evenorodd.setStatusBar(self.statusbar)

        self.retranslateUi(evenorodd)
        QtCore.QMetaObject.connectSlotsByName(evenorodd)
        
        self.btnCheck.clicked.connect(self.evenoroddcheck) #Calling the function when the check button is clicked.
        

    def retranslateUi(self, evenorodd):
        _translate = QtCore.QCoreApplication.translate
        evenorodd.setWindowTitle(_translate("evenorodd", "Even or Odd"))
        self.lblNumber.setText(_translate("evenorodd", "Enter a number "))
        self.btnCheck.setText(_translate("evenorodd", "Check "))
        self.lblResult.setText(_translate("evenorodd", "Result"))
        
    def evenoroddcheck(self):
        input_number = self.txtNumber.text() # Retriving the value enetered by the user and stroed in input_number
        if(input_number.isdigit()):
            
            input_number = int(input_number)
            if(input_number%2 == 0):
                self.txtResult.setText("Number is Even")
            else:
                self.txtResult.setText("Number is Odd") 
        else:
            # create a new messageBox instances for input error
            msg = QMessageBox()
            msg.setText("Please enter a valid number")
            msg.setWindowTitle("Even or Odd")
            msg.exec()
    
            
        
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    evenorodd = QtWidgets.QMainWindow()
    ui = Ui_evenorodd()
    ui.setupUi(evenorodd)
    evenorodd.show()
    sys.exit(app.exec())
