# Form implementation generated from reading ui file 'fullname.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FullName(object):
    def setupUi(self, FullName):
        FullName.setObjectName("FullName")
        FullName.resize(876, 645)
        self.centralwidget = QtWidgets.QWidget(parent=FullName)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFirstName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFirstName.setGeometry(QtCore.QRect(60, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblFirstName.setFont(font)
        self.lblFirstName.setObjectName("lblFirstName")
        self.txtFirstName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtFirstName.setGeometry(QtCore.QRect(170, 80, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtFirstName.setFont(font)
        self.txtFirstName.setObjectName("txtFirstName")
        self.lblLastName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLastName.setGeometry(QtCore.QRect(60, 120, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblLastName.setFont(font)
        self.lblLastName.setObjectName("lblLastName")
        self.txtLastName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLastName.setGeometry(QtCore.QRect(170, 120, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtLastName.setFont(font)
        self.txtLastName.setObjectName("txtLastName")
        self.btnFullName = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnFullName.setGeometry(QtCore.QRect(180, 170, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnFullName.setFont(font)
        self.btnFullName.setObjectName("btnFullName")
        self.lblResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(60, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblResult.setFont(font)
        self.lblResult.setObjectName("lblResult")
        self.txtResult = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtResult.setGeometry(QtCore.QRect(150, 210, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtResult.setFont(font)
        self.txtResult.setObjectName("txtResult")
        FullName.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=FullName)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 876, 21))
        self.menubar.setObjectName("menubar")
        FullName.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=FullName)
        self.statusbar.setObjectName("statusbar")
        FullName.setStatusBar(self.statusbar)

        self.retranslateUi(FullName)
        QtCore.QMetaObject.connectSlotsByName(FullName)
        # Calling the new function by clicking the bottom 
        self.btnFullName.clicked.connect(self.display_full_name)
 

    def retranslateUi(self, FullName):
        _translate = QtCore.QCoreApplication.translate
        FullName.setWindowTitle(_translate("FullName", "Full Name"))
        self.lblFirstName.setText(_translate("FullName", "Enter First Name "))
        self.lblLastName.setText(_translate("FullName", "Enter Last Name "))
        self.btnFullName.setText(_translate("FullName", "Full Name"))
        self.lblResult.setText(_translate("FullName", "Full Name"))
      # Creating a new function display name by user input
    def display_full_name(self):
        first_name = self.txtFirstName.text() 
        last_name = self.txtLastName.text()
        full_name = first_name + " " + last_name
        self.txtResult.setText(full_name)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FullName = QtWidgets.QMainWindow()
    ui = Ui_FullName()
    ui.setupUi(FullName)
    FullName.show()
    sys.exit(app.exec())
