# Form implementation generated from reading ui file 'gradecalculator.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox 

class Ui_GradeCalcualtor(object):
    def setupUi(self, GradeCalcualtor):
        GradeCalcualtor.setObjectName("GradeCalcualtor")
        GradeCalcualtor.resize(1891, 934)
        self.centralwidget = QtWidgets.QWidget(parent=GradeCalcualtor)
        self.centralwidget.setObjectName("centralwidget")
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(210, 150, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblScore.setFont(font)
        self.lblScore.setObjectName("lblScore")
        self.lblGrade = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblGrade.setGeometry(QtCore.QRect(210, 350, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblGrade.setFont(font)
        self.lblGrade.setObjectName("lblGrade")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(360, 160, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtScore.setFont(font)
        self.txtScore.setObjectName("txtScore")
        self.txtGrade = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtGrade.setGeometry(QtCore.QRect(360, 350, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtGrade.setFont(font)
        self.txtGrade.setObjectName("txtGrade")
        self.btnCalcualte = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalcualte.setGeometry(QtCore.QRect(370, 250, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnCalcualte.setFont(font)
        self.btnCalcualte.setObjectName("btnCalcualte")
        GradeCalcualtor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=GradeCalcualtor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1891, 21))
        self.menubar.setObjectName("menubar")
        GradeCalcualtor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=GradeCalcualtor)
        self.statusbar.setObjectName("statusbar")
        GradeCalcualtor.setStatusBar(self.statusbar)

        self.retranslateUi(GradeCalcualtor)
        QtCore.QMetaObject.connectSlotsByName(GradeCalcualtor)
        # When the Calcualte Grade bottom is cliked action is called 
        self.btnCalcualte.clicked.connect(self.grade_calculator)

    def retranslateUi(self, GradeCalcualtor):
        _translate = QtCore.QCoreApplication.translate
        GradeCalcualtor.setWindowTitle(_translate("GradeCalcualtor", "Grade Calculator"))
        self.lblScore.setText(_translate("GradeCalcualtor", "Enter Student Score"))
        self.lblGrade.setText(_translate("GradeCalcualtor", "Student Grade"))
        self.btnCalcualte.setText(_translate("GradeCalcualtor", "Calculate Grade"))

    def grade_calculator(self):
        input_score = self.txtScore.text()
        grade= ""
        msg = QMessageBox()
        msg.setWindowTitle("Grade Calculator")  # Corrected line

        if(input_score.isdigit()): #valid score
            input_score = int(input_score)
            if(input_score <101):
                if(input_score >= 90):
                    grade = "A"
                elif(input_score >= 80):
                    grade = "B"
                elif(input_score >= 70):
                    grade = "C"
                elif(input_score >= 60):
                    grade = "D"
                else:
                    grade = "F"
                self.txtGrade.setText(grade)
            else:
                msg.setText("Please enter a score between 0 and 100")
                msg.exec()
        else:
            msg.setText("Please enter a valid score")
            msg.exec()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GradeCalcualtor = QtWidgets.QMainWindow()
    ui = Ui_GradeCalcualtor()
    ui.setupUi(GradeCalcualtor)
    GradeCalcualtor.show()
    sys.exit(app.exec())