# Form implementation generated from reading ui file 'helloworld.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from PyQt6.QtWidgets import QMessageBox

class Ui_HelloWorld(object):
    def setupUi(self, HelloWorld):
        HelloWorld.setObjectName("HelloWorld")
        HelloWorld.resize(1130, 908)
        self.centralwidget = QtWidgets.QWidget(parent=HelloWorld)
        self.centralwidget.setObjectName("centralwidget")
        self.btnGreeting = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnGreeting.setGeometry(QtCore.QRect(490, 290, 121, 41))
        self.btnGreeting.setObjectName("btnGreeting")
        HelloWorld.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=HelloWorld)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1130, 21))
        self.menubar.setObjectName("menubar")
        HelloWorld.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=HelloWorld)
        self.statusbar.setObjectName("statusbar")
        HelloWorld.setStatusBar(self.statusbar)

        self.retranslateUi(HelloWorld)
        QtCore.QMetaObject.connectSlotsByName(HelloWorld)
        # When the button is clicked, call the display_messsage function 
        self.btnGreeting.clicked.connect(self.display_message)

    def retranslateUi(self, HelloWorld):
        _translate = QtCore.QCoreApplication.translate
        HelloWorld.setWindowTitle(_translate("HelloWorld", "Hello World"))
        self.btnGreeting.setText(_translate("HelloWorld", "Click Me"))
     # self reserve to the function being part of the application 
    def display_message(self):
        # create a new instance of a message box
        msg = QMessageBox() 
        msg.setText("Hello World")
        msg.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HelloWorld = QtWidgets.QMainWindow()
    ui = Ui_HelloWorld()
    ui.setupUi(HelloWorld)
    HelloWorld.show()
    sys.exit(app.exec())
